#!/usr/bin/python
# Author: Pentestical
# Titel: Fehlercode "SSL_ERROR_RX_RECORD_TOO_LONG" - hier die Lösung
# Beschreibung: In 3 Schritten den Fehler fixen

# 1) füge am Anfang deines Codes die Bibliothek "ssl" hinzu :
import ssl

# 2) füge die folgende Zeile hinzu, um SSL Fehlermeldungen zu ignorieren:
requests.packages.urllib3.disable_warnings()

# 3) diese Fehlermeldung bedeutet, dass du vermutlich die Methode "requests" benutzt im Code (um eine Web-Anfrage zu stellen). Suche im Code nach ALLEN requests, und füge ganz ans
# Ende noch hinzu "verify=False". Beispiel, statt:

requests.get(url, headers=headers)

# würdest du schreiben :

requests.get(url, headers=headers, verify=False)

# wiederhole das für alle (!) "requests", die du finden kannst. Problem gelöst, viel Spaß
